version: '2.3'

services:
  realsense:
    image: iory/docker-ros-d415
    container_name: realsense
    privileged: true
    environment:
      - "ROS_HOSTNAME=realsense"
      - "ROS_MASTER_URI=http://realsense:11311"
    command: roslaunch realsense2_camera rs_rgbd.launch

  mask_rcnn:
    image: hirokiyokoyama/mask_rcnn_ros
    container_name: mask_rcnn
    runtime: nvidia
    environment:
      - "ROS_HOSTNAME=mask_rcnn"
      - "ROS_MASTER_URI=http://realsense:11311"
    command: rosrun mask_rcnn mask_rcnn_node.py image:=/camera/color/image_rect_color

  visualize:
    image: hirokiyokoyama/mask_rcnn_ros
    container_name: visualize
    environment:
      - "ROS_HOSTNAME=visualize"
      - "ROS_MASTER_URI=http://realsense:11311"
      - "DISPLAY=$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun mask_rcnn visualize.py image:=/camera/color/image_rect_color

