version: '2.3'

services:
  openni2:
    image: hirokiyokoyama/openni2_ros
    container_name: openni2
    privileged: true
    environment:
      - "ROS_HOSTNAME=openni2"
      - "ROS_MASTER_URI=http://openni2:11311"
    command: roslaunch openni2_launch openni2.launch

  mask_rcnn:
    image: hirokiyokoyama/openpose_ros
    container_name: openpose
    runtime: nvidia
    environment:
      - "ROS_HOSTNAME=mask_rcnn"
      - "ROS_MASTER_URI=http://openni2:11311"
    command: rosrun openpose_ros openpose.py image:=/camera/rgb/image_rect_color

  visualize:
    image: hirokiyokoyama/openpose_ros
    container_name: visualize
    environment:
      - "ROS_HOSTNAME=visualize"
      - "ROS_MASTER_URI=http://openni2:11311"
      - "DISPLAY=unix$DISPLAY"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: rosrun openpose_ros visualize.py image:=/camera/rgb/image_rect_color

